services:
  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy
  #   container_name: ci_cd_nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - certs:/etc/nginx/certs:ro
  #     - vhost:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   networks:
  #     - ci_cd
  #   restart: always

  # acme-companion:
  #   image: nginxproxy/acme-companion
  #   container_name: ci_cd_nginx-proxy-acme
  #   volumes_from:
  #     - nginx-proxy
  #   volumes:
  #     - certs:/etc/nginx/certs:rw
  #     - acme:/etc/acme.sh
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   networks:
  #     - ci_cd
  #   restart: always
  #   depends_on:
  #     - nginx-proxy

  jenkins:
    build:
      dockerfile: Dockerfile
      context: ./main
    networks:
      - ci_cd
    restart: always
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: ci_cd_jenkins
    environment:
      - VIRTUAL_HOST=cicd.stroalgo.net
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=cicd.stroalgo.net
      - LETSENCRYPT_EMAIL=stroalgo@gmail.com
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  

  linux_agent:
    container_name: ci_cd_jenkins_linux_agent
    build:
      dockerfile: Dockerfile
      context: ./agents/linux
    networks:
      - ci_cd
    restart: always
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins

  sonarqube:
    container_name: ci_cd_sonar
    image: sonarqube:9.9-community
    networks:
      - ci_cd
    depends_on:
      - sonarqube-database
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-database:5432/sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    restart: always
    ports:
      - 9000:9000

  sonarqube-database:
    container_name: ci_cd_database
    image: postgres:18.2
    networks:
      - ci_cd
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
    volumes:
      - sonarqube_database:/var/lib/postgresql      
    restart: always
    ports:
      - 5432:5432

  nexus:
    container_name: ci_cd_nexus
    image: sonatype/nexus3:3.89.1
    restart: always
    volumes:
      - nexus-data:/sonatype-work
    ports:
      - 8081:8081

volumes:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_database:  
  certs:
  vhost:
  html:
  acme:  
  nexus-data: {}

networks:
   ci_cd:
    name:  ci_cd
