version: "3.9"
services:
  jenkins:
    build:
      dockerfile: Dockerfile
      context: ./main
    networks:
      - ci_cd
    restart: always
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: ci_cd_jenkins
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  linux_agent:
    container_name: ci_cd_jenkins_linux_agent
    build:
      dockerfile: Dockerfile
      context: ./agents/linux
    networks:
      - ci_cd
    restart: always
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  windows_agent:
    container_name: ci_cd_jenkins_windows_agent
    build:
      dockerfile: Dockerfile
      context: ./agents/windows
    networks:
      - ci_cd
    restart: always
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    # environment:
    #   - JENKINS_URL=http://172.17.0.1:8080/
    #   - JENKINS_AGENT_NAME=Docker-Agent-Windows
    #   - JENKINS_SECRET=6eb092631e70cddee8b9906627cc6a4b8af3a7ef5d181aca79e93198e10ad240

  windows_11:
    image: dockurr/windows
    container_name: windows_11
    networks:
      - ci_cd
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    tty: true
    environment:
      VERSION: "win11"
      RAM_SIZE: "2.5G"
      CPU_CORES: "4"
      DISK_SIZE: "90G"
      KVM: "N"
      CONSOLE: "Y"
      HV: "N"
    volumes:
      - /var/win:/storage
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    container_name: ci_cd_sonar
    image: sonarqube:9.9-community
    networks:
      - ci_cd
    depends_on:
      - sonarqube-database
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-database:5432/sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    restart: always
    ports:
      - 9000:9000

  sonarqube-database:
    container_name: ci_cd_database
    image: postgres
    networks:
      - ci_cd
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
    volumes:
      - sonarqube_database:/var/lib/postgresql
      - sonarqube_database_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

  nexus:
    container_name: ci_cd_nexus
    image: sonatype/nexus3
    restart: always
    volumes:
      - nexus-data:/sonatype-work
    ports:
      - 8081:8081

volumes:
  sonarqube_database_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_database:
  sonarqube_extensions:
  nexus-data: {}

networks:
  ci_cd:
